---
- name Setup Motiavlogic Bastion Host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import bastion variables
      include_vars: vars/bastion_setup

    - name: Import VPC setup output variables
      include_vars: vars/output_vars

####################################################
    - name: Creating ec2 key pair
      ec2_key:
        name: Motiva-Bastion-Key
        region: "{{ region }}"
      register: key_out

    - name: Save Bastion login key into a file name as bastion-key.pem
      copy:
        contents: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

####################################################
    - name: Create Bastion host security group rule descriptions
      ec2_group:
        name: Motiva-Bastion-Host-SG
        description: allow port 22 from anywhere and lall port within sg
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
         - proto: tcp
           from_port: 22
           to_port: 22
           cidr_ip: "{{ MY_IP }}"
           rule_desc: allow all on port 22
      register: BastionSG_out

####################################################
    - name: Create Bastion Host Instance
      ec2:
        key_name: Motiva-Bastion-Key
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        region: "{{ region }}"
        exact_count: 1
        assign_public_ip: yes
        instance_tags:
          Name: "Bastion_host"
          Project: Ansible_project
          Owner: Motiva_Devops_Team
        count_tag:
          Name: "Bastion_host"
          Project: Ansible_project
          Owner: Motiva_Devops_Team
        group_id: "{{ BastionSG_out.group_id }}"
        vpc_subnet_id: "{{ Motiva_pubSub1_id }}"
      register: Bastion_host_out





