- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup

    - name: Create vprofile VPC
      ec2_vpc_net:
         name: "{{ vpc_name }}"
         cidr_block: "{{ vpcCidr }}"
         region: "{{ region }}"
         dns_support: yes
         dns_hostnames: yes
         tenancy: default
         state: "{{ state }}"
      register: vpcout

    - debug:
          var: vpcout

    - name: Create subnet for the Ec2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        cidr: "{{ PubSub1Cidr}}"
        state: "{{ state }}"
        az: "{{ zone1 }}"
        map_public: yes
        region: "{{ region }}"
        tags:
          Name: Public Subnet1
      register: motiva_pubsub1

    - debug:
          var: motiva_pubsub1