- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup

    - name: Create vprofile VPC
      ec2_vpc_net:
         name: "{{ vpc_name }}"
         cidr_block: "{{ vpcCidr }}"
         region: "{{ region }}"
         dns_support: yes
         dns_hostnames: yes
         tenancy: default
         state: "{{ state }}"
      register: vpcout

#    - debug:
#          var: vpcout

    - name: Create first public subnet for the Ec2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        cidr: "{{ PubSub1Cidr }}"
        state: "{{ state }}"
        az: "{{ zone1 }}"
        map_public: yes
        region: "{{ region }}"
        tags:
          Name: Public Subnet1
      register: motiva_pubsub1

    - debug:
          var: motiva_pubsub1

    - name: Create second public subnet for the Ec2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        cidr: "{{ PubSub2Cidr }}"
        state: "{{ state }}"
        az: "{{ zone2 }}"
        map_public: yes
        region: "{{ region }}"
        tags:
          Name: Public Subnet2
      register: motiva_pubsub2

    - debug:
          var: motiva_pubsub2

    - name: Create subnet for the Ec2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        cidr: "{{ PubSub3Cidr }}"
        state: "{{ state }}"
        az: "{{ zone3 }}"
        map_public: yes
        region: "{{ region }}"
        tags:
          Name: Public Subnet3
      register: motiva_pubsub3

    - debug:
          var: motiva_pubsub3


    - name: Create Private subnet for the Ec2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        cidr: "{{ PrivSub4Cidr }}"
        state: "{{ state }}"
        az: "{{ zone1 }}"
        map_public: yes
        region: "{{ region }}"
        tags:
          Name: Private Subnet1
      register: motiva_privsub1

    - debug:
          var: motiva_privsub1

    - name: Create Private subnet for the Ec2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        cidr: "{{ PrivSub5Cidr }}"
        state: "{{ state }}"
        az: "{{ zone1 }}"
        map_public: yes
        region: "{{ region }}"
        tags:
          Name: Private Subnet2
      register: motiva_privsub2

    - debug:
          var: motiva_privsub3


    - name: Create Private subnet for the Ec2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        cidr: "{{ PrivSub6Cidr }}"
        state: "{{ state }}"
        az: "{{ zone1 }}"
        map_public: yes
        region: "{{ region }}"
        tags:
          Name: Private Subnet6
      register: motiva_privsub6

    - debug:
          var: motiva_privsub6