---
- name: Generate artifact, copy artifact & sql file to files directory
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install jdj, Maven, git
      apt:
        name: "{{ item }}"
        state: present
        update_caache: yes
      loop:
        - git
        - openjdk-8-jdk
        - maven

    - name: clone source code from github
      git:
        repo: 'https://github.com/devopshydclub/vprofile-project.git'
        dest: ./motivalogic-repo
        version: motiva-rem
      register: git_status

    - name: mvn install command to build artifact
      command: " mvn install"
      args:
        chdir: motivalogic-repo
      when: git_status.changed
      register: mvn_info

    - name: Copy artifacts to files directory
      copy:
        src: "{{ item }}"
        dest: files/ROOT.war
      with_fileglob: motivalogic-repo/target/*.war

    - name: Copy SQL file to files directory
      copy:
        src: motivalogic-repo/src/main/resources/db_backup.sql
        dest: files/db_backup.sql
