---
- name: Build Artifact ROOT.war & SQL file to be copied in files/ directory
  import_playbook: build.yml

- name: Set Host to IP Mapping in /etc/hosts file of all servers
  import_playbook: set_host_ip_map.yml

- name: Setup dbserver
  import_playbook: db.yml

- name: Deploy SQL file on DPserver
  import_playbook: dbdeploy.yml

- name: Setup Memcached service
  import_playbook: memcached.yml

- name: Setup RabbitMQ service
  import_playbook: rabbitmq.yml

- name: Setup Tomcat Application server
  import_playbook: appserver.yml

- name: Setup Nginx webserver
  import_playbook: web01.yml
